### PR TITLE
Implement no_std support

### PR DESCRIPTION
**Pull request by CryZe**
This implements no_std support for unicase. It adds a feature called `std` which is activated by default. no_std support has been implemented for every Rust version starting with 1.36 which added stable support for the alloc crate. All of unicase's features are available on no_std.

### CODE REVIEW

**Comment by CryZe** [comment]
What I don't quite like is that I needed to add the feature at all. Since it doesn't really do anything, there shouldn't be any need for it. But examples in docs are apparently not compiled with cfg(test), so they are compiled without std, which then makes them complain that no global allocator is set. This is really stupid and should honestly be fixed in Rust's testing framework.

**Comment by seanmonstar** [comment]
So, is the purpose of the feature **only** so the doc tests can pass? If so, maybe we just make the feature semi-private, like `__internal_docs_std` or whatever.

**Comment by CryZe** [comment]
I removed the feature entirely now. It's really just a bug in Rust's test framework and interestingly, the tests pass regardless of it printing an error (it also runs all of them). And it seems like on nightly the bug is fixed anyway. So I'd say it's not worth adding a feature.

**Comment by CryZe** [comment]
Rebased onto latest master.

**Comment by CryZe** [comment]
What's the status of this PR? It's good to go from my side.

**Comment by CryZe** [comment]
Can this be merged? I'm beginning to get blocked by this soon.

**Comment by CryZe** [comment]
Thanks, considering there's also not a lot going on in this repository (as unicase is in a fairly stable shape), would you mind creating a release for this as well? (Otherwise I fear it could possibly take quite a long time for another release).

**Pull request merged**
