### PR TITLE
fix: hash for Unicode will call write_u8 like Ascii does

### LINKED ISSUE #72: incorrect hash impl
https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq
> When implementing both Hash and [Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html), it is important that the following property holds:
> `k1 == k2 -> hash(k1) == hash(k2)`
> In other words, if two keys are equal, their hashes must also be equal

`UniCase<S: AsRef<str>>` implements `Hash + Eq`, so the above requirement must be satisfied. The following test case fails:

```rust
use std::hash::BuildHasher;
use foldhash::quality::RandomState;
use unicase::UniCase;

let k1 = UniCase::unicode("Foo");
let k2 = UniCase::new("foO");

assert_eq!(k1, k2);

let h = RandomState::default();
assert_eq!(h.hash_one(k1), h.hash_one(k2));
```

This occurs because `UniCase::unicode` produces `b"f", b"o", b"o"`, while `UniCase::new` (with ascii) produces `b'f', b'o', b'o'`, which is not guaranteed to be the same under `Hasher`.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #72 

cc @conradludgate @orlp

### CODE REVIEW

**Comment by seanmonstar** [comment]
Crazy personal opinion: that probably should yell at you and die.

**Comment by marvin-j97** [comment]
To make it worse, "Maße" means something like "measurements", while "Masse" means "mass" (as in weight or group of things/people), so they aren't even the same word.

**Comment by seanmonstar** [comment]
Words that are spelled exactly the same can have different meanings based on context. This crate is not trying to say the words mean the same thing. It's saying that according to the Unicode Case Folding algorithm, they are equivalent for matching purposes.

**Comment by conradludgate** [comment]
Putting it into a more formal specification. It's a logic bug if you use UniCase::ascii with non-ascii text, thus any inconsistencies are the fault of the user here and not the library. LGTM

**Review by conradludgate — APPROVED** [review]

**Pull request merged**
