### PR TITLE
Update rustc_version dep to 0.2

### PR DESCRIPTION
**Pull request by Kimundi**
See https://github.com/Kimundi/rustc-version-rs/issues/12

### CODE REVIEW

**Comment by seanmonstar** [comment]
Looks like the travis build failed for Rust 1.3, cause the newer version needs newer Rust. So, exactly the reason I'm using `rustc_version` (to keep working on oldest possible Rust) prevents me from upgrading :D

**Comment by Kimundi** [comment]
Heh, seems I have to investigate correct backwards compatibility a bit deeper then :)

**Comment by Kimundi** [comment]
Actually, seems that the issue stems from semver not being compatible with 1.3, so I'm not sure how to proceed there.

**Comment by seanmonstar** [comment]
Looks like `semver-parser` was rewritten to not use regex, and in that commit, it started using the `?` operator: https://github.com/steveklabnik/semver-parser/commit/2b8cc56600b53d157281a4eed023dc8b45992a83

Also looks like that's starting with semver-parser@0.7, which semver started relying on in semver@0.6.

Is there bugs or something horrible that can happen in my usage of rustc_version 0.1? If not, I'd probably just leave at 0.1 until the world has moved past rust 1.15 (ha!).

**Pull request closed without merging**
